services:
  - type: web
    name: streamify-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_HOSTNAME
        sync: false
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: streamify-movies
      - key: OPENAI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-ada-002
      - key: EMBEDDING_DIMENSION
        value: 1536
